denoising_net: resnet
hidden_dim: 32
dropout_prob: 0 
n_blocks: 3
embedding_dim: 20
conditional: True
normalization: none
is_binarized: False
embed_size_factor: False
conditioning_probability: 0.8
guided_conditioning: True
