dataset_path: ../../project_folder/datasets/processed_full_genome/dentategyrus/dentategyrus_train.h5ad
layer_key: X_counts
covariate_keys: [clusters]
subsample_frac: 1
normalization_type: log_gexp
is_binarized: False 
theta_covariate: clusters
split_rates: [0.90, 0.10]