dataset_path: ../../project_folder/datasets/processed/classifier_experiment_pbmc/pbmc_covid_train.h5ad
layer_key: X_counts
covariate_keys: [cell_type]
subsample_frac: 1
normalization_type: log_gexp
is_binarized: False 
theta_covariate: cell_type
split_rates: [0.90, 0.10]