dataset_path: ../../project_folder/datasets/processed/atac/pbmc/pbmc10k_multiome_train.h5mu
layer_key: X_counts
covariate_keys: [cell_type]
subsample_frac: 1
normalization_type: log_gexp
is_binarized: True 
theta_covariate: cell_type
split_rates: [0.90, 0.10]