dataset_path: ../../project_folder/datasets/processed_full_genome/tabula_muris/tabula_muris_train.h5ad
layer_key: X_counts
covariate_keys: [tissue]
subsample_frac: 1
normalization_type: log_gexp
is_binarized: False 
theta_covariate: tissue
split_rates: [0.90, 0.10]